name: educate_io
version: 1.0.0+1
publish_to: none
description: Platform to find private tutors
environment:
  sdk: ">=2.90.0 <4.0.0"


dependencies:
  animated_list_plus: ^0.4.5
  bitmap: ^0.1.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  crop_your_image: ^0.7.4
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.0
  fast_image_resizer: ^0.0.2
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flex_color_picker: ^3.1.0
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^3.1.0
  flutter_cache_manager: ^3.3.0
  flutter_google_places: ^0.3.0
  flutter_google_places_sdk: ^0.3.2+6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  flutter_phone_direct_caller: ^2.1.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.1
  google_maps_flutter: ^2.2.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^5.4.4
  image: ^4.0.13
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  path: ^1.8.3
  path_provider: 2.0.12
  url_launcher: ^6.1.8
  



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/google_logo.svg
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: assets\fonts\NotoSans-Regular.ttf

flutter_native_splash:
  image: assets/light_mode.png
  color: "#ffffff"
  image_dark: assets/dark_mode.png
  color_dark: "#1a1a1a"
  android_12:
    image: assets/android_12_light_mode.png
    color: "#ffffff"
    image_dark: assets/android_12_dark_mode.png
    color_dark: "#1a1a1a"
  android12: true
  android: true
  ios: true
